// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
      link: {
        type: 'doc',
        id: 'intro',
      },
    },
    {
      type: 'category',
      label: 'Module 1: Physical AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-physical-ai',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Humanoid Control',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-humanoid-control',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone-project',
        },
      ],
    },
    {
      type: 'category',
      label: 'Additional Resources',
      items: [
        'embodied-intelligence-setup',
        'simulation-setup',
        'deployment-guide',
        'security-considerations',
        'content-verification',
        'reproducibility-testing',
        'reproducibility-verification',
      ],
    },
  ],
};

module.exports = sidebars;